version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - janbarasek
  ignore:
  - dependency-name: ramsey/uuid
    versions:
    - 4.1.1
