<?php

use Baraja\Doctrine\DBAL\Utils\QueryUtils;
use Baraja\Doctrine\Logger\Event;
use Baraja\Url\Url;
use Tracy\Helpers;

$qs = '';
$qExpress = '';
$isTransaction = false;
$select = 0;
$insert = 0;
$update = 0;
$delete = 0;
$other = 0;
$queryId = 1;
$timeBlocks = [];

/**
 * @var Event[] $events
 */

foreach ($events ?? [] as $event) {
	$background = null;

	if ($event->getSql() === '"START TRANSACTION"') {
		$isTransaction = true;
		$background = 'rgb(204,255,204)';
	}
	if ($event->getSql() === '"COMMIT"' || $event->getSql() === '"ROLLBACK"') {
		$isTransaction = false;
		$background = 'rgb(253,169,157)';
	}
	if ($isTransaction === true && $background === null) {
		$background = 'rgb(255,244,204)';
	}

	$queryParser = explode(' ', strtoupper(trim($event->getSql())), 2);
	$durationMs = $event->getDuration() !== null ? $event->getDuration() * 1000 : null;

	if (isset($queryParser[1])) {
		switch ($queryParser[0]) {
			case 'SELECT':
				$select++;
				break;
			case 'INSERT':
				$insert++;
				break;
			case 'UPDATE':
				$update++;
				break;
			case 'DELETE':
				$delete++;
				break;
			default:
				$other++;
				break;
		}
	}

	$trackingUrl = Url::get()->getNetteUrl();
	$trackingUrl->setQueryParameter('trackingSqlEnabled', true);
	$trackingUrl->setQueryParameter('trackingSqlHash', $event->getHash());

	$durationColor = Baraja\Doctrine\DBAL\Tracy\QueryPanel\QueryPanel::getPanelDurationColor($durationMs);
	$renderedQuery = '<tr id="doctrineQuery_' . $queryId . '">'
		. '<td' . ($durationColor !== null ? ' style="' . $durationColor . '"' : '') . '>'
		. ($durationMs !== null
			? '<span title="' . number_format($durationMs, 8, '.', ' ') . ' ms">'
			. number_format($durationMs, 2, '.', ' ')
			. '</span>'
			: '<span style="color:white;background:#bf0014;padding:2px 6px;border-radius:4px">Error</span>'
		)
		. '<br><i title="Request runtime delay time">' . number_format($event->getDelayTime(), 2, '.', '') . '</i>'
		. '<br><a href="' . $trackingUrl->getAbsoluteUrl() . '">Track</a>'
		. ($isTransaction ? '<br><span style="color:#bf0014">•</span>' : '')
		. '</td>'
		. '<td class="tracy-dbal-sql" ' . ($background ? ' style="background:' . $background . ' !important"' : '') . '>'
		. ($event->getDuration() === null
			? '<div style="color:white;background:#bf0014;text-align:center;padding:2px 6px;margin:8px 0;border-radius:4px">Error with processing this query!</div>'
			: '')
		. QueryUtils::highlight($event->getSql())
		. ($event->getLocation() !== null
			? '<hr>' . Helpers::editorLink($event->getLocation()['file'], $event->getLocation()['line'])
			: ''
		) . '</td></tr>';
	$timeBlocks[] = '<td style="text-align:center;padding:0;' . ($durationColor !== null ? '' . $durationColor . '' : 'width:15px') . '">'
		. '<a href="#doctrineQuery_' . $queryId . '">' . ((int) round($durationMs)) . '</a>'
		. '</td>';

	if ($event->getDuration() !== null) {
		$qs .= $renderedQuery;
	} else {
		$qExpress .= $renderedQuery;
	}

	$queryId++;
}

?>
<style>
	#tracy-debug td.tracy-dbal-sql {
		background: white !important
	}

	#tracy-debug .tracy-dbal-source {
		color: #999 !important
	}

	#tracy-debug .tracy-dbal tr table {
		margin: 8px 0;
		max-height: 150px;
	}
</style>

<?php

if ($events === []) {
	echo '<h1>No queries</h1>';
} else {
	?>
	<h1>Queries:
	  <?php

	  $queriesDurationColor = Baraja\Doctrine\DBAL\Tracy\QueryPanel\QueryPanel::getPanelDurationColor($totalTime ?? 0 * 1000);
	  echo ($queriesCount ?? '0')
		  . (isset($totalTime) === false
			  ? ''
			  : ', <span' . ($queriesDurationColor ? ' style="' . $queriesDurationColor . ';padding:0 5px"' : '') . '>time: '
			  . number_format($totalTime ?? 0 * 1000, 1, '.', ' ')
			  . ' ms</span>'
		  ) . ' [' . trim(
			  ($select > 0 ? $select . '<span style="font-size:14pt">&times;select</span> ' : '')
			  . ($update > 0 ? $update . '<span style="font-size:14pt">&times;update</span> ' : '')
			  . ($insert > 0 ? $insert . '<span style="font-size:14pt">&times;insert</span> ' : '')
			  . ($delete > 0 ? $delete . '<span style="font-size:14pt">&times;delete</span> ' : '')
			  . ($other > 0 ? $other . '<span style="font-size:14pt">&times;other</span>' : '')
		  ) . ']';
	  ?>
	</h1>
<?php } ?>

<div class="tracy-inner nettrine-dbal">
	<?= ($timeBlocks !== []
		? '<table><tr>' . implode('', $timeBlocks) . '</tr></table>'
		: '');
	?>
	<table>
		<tr>
			<th style="max-width:48px;border-top:0">ms</th>
			<th style="padding:0;border-top:0">
				<table>
					<tr>
						<th style="border:0">
							SQL Statement
							(<?= ($invalidCache ?? false
							? '<span style="color:#bf0014">invalid cache!</span>'
							: 'Cache: ' . (isset($cache) === false || ($cache ?? null) === null ? 'NO CACHE' : get_class($cache ?? '')));
							?>)
						</th>
						<th style="border:0;width:32px;text-align:center;padding:2px 0">
							<a href="https://github.com/baraja-core/doctrine" target="_blank">HELP</a>
						</th>
					</tr>
				</table>
			</th>
		</tr>
	  <?= $qExpress . $qs ?>
	</table>
	<?php

	if (($connected ?? false) === false) {
		echo '<div style="text-align:center;padding:1em 0;color:#888">Database is disconnected.</div>';
	} elseif ($events === []) {
		echo '<div style="text-align:center;padding:1em 0;color:#888">No queries.</div>';
	}
	if (count($events) < ($queriesCount ?? 0)) {
		echo '<div style="text-align:center;padding:48px">'
			. 'And more...'
			. '</div>';
	}
	?>
</div>
